version: 0.2

# Buildspec for building and deploying Frontend

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Node version..."
      - node --version
      - npm --version

  pre_build:
    commands:
      - echo "Environment - $ENVIRONMENT"
      - echo "Frontend Bucket - $FRONTEND_BUCKET"
      
      # Read API Gateway URL from infrastructure output
      - |
        if [ -f api_gateway_url.txt ]; then
          export API_GATEWAY_URL=$(cat api_gateway_url.txt)
          echo "API Gateway URL from artifact - $API_GATEWAY_URL"
        else
          echo "Using environment variable API Gateway URL - $API_GATEWAY_URL"
        fi
      
      - cd frontend

  build:
    commands:
      - echo "Installing dependencies..."
      - npm ci
      
      - echo "Creating production environment file..."
      - |
        cat > .env.production << EOF
        VITE_API_URL=$API_GATEWAY_URL
        VITE_ENV=production
        EOF
      
      - echo "Building frontend..."
      - npm run build
      
      - echo "Deploying to S3..."
      - aws s3 sync dist/ s3://$FRONTEND_BUCKET/ --delete
      
      - echo "Invalidating CloudFront cache (if exists)..."
      - |
        echo "Checking for CloudFront distribution..."
        DISTRIBUTION_ID=$(aws cloudfront list-distributions \
          --query "DistributionList.Items[?Origins.Items[?DomainName=='$FRONTEND_BUCKET.s3.amazonaws.com']].Id" \
          --output text 2>/dev/null || echo "")
        
        if [ ! -z "$DISTRIBUTION_ID" ] && [ "$DISTRIBUTION_ID" != "None" ] && [ "$DISTRIBUTION_ID" != "null" ]; then
          echo "Found CloudFront distribution: $DISTRIBUTION_ID"
          echo "Creating cache invalidation..."
          aws cloudfront create-invalidation \
            --distribution-id "$DISTRIBUTION_ID" \
            --paths "/*" || echo "Invalidation failed, but continuing..."
        else
          echo "No CloudFront distribution found for bucket: $FRONTEND_BUCKET"
          echo "Frontend will be served directly from S3"
        fi

  post_build:
    commands:
      - echo "Frontend deployment completed"
      - echo "Frontend URL - http://$FRONTEND_BUCKET.s3-website.$AWS_DEFAULT_REGION.amazonaws.com"
      - cd ..

artifacts:
  files:
    - frontend/dist/**/*
  name: FrontendOutput

cache:
  paths:
    - 'frontend/node_modules/**/*'
