version: 0.2

# Buildspec for deploying infrastructure with Terraform

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies...unzip, wget and curl"
      - apt-get update -y
      - apt-get install -y unzip wget curl
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip -o terraform_1.6.6_linux_amd64.zip
      - chmod +x terraform
      - sudo mv terraform /usr/local/bin/terraform
      - terraform --version

  pre_build:
    commands:
      - echo "Configuring AWS credentials..."
      - aws sts get-caller-identity
      - echo "Environment - $ENVIRONMENT"
      - cd terraform

  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init -backend-config="key=$ENVIRONMENT/terraform.tfstate"
      
      - echo "Planning Terraform changes..."
      - |
        if [ "$ENVIRONMENT" = "prod" ]; then
          terraform plan -var-file="terraform.prod.tfvars" -out=tfplan
        else
          terraform plan -var-file="terraform.dev.tfvars" -out=tfplan
        fi
      
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve tfplan
      
      - echo "Getting API Gateway URL..."
      - export API_GATEWAY_URL=$(terraform output -raw api_gateway_url)
      - echo "API Gateway URL - $API_GATEWAY_URL"
      - echo $API_GATEWAY_URL > ../api_gateway_url.txt

  post_build:
    commands:
      - echo "Infrastructure deployment completed"
      - cd ..

artifacts:
  files:
    - api_gateway_url.txt
  name: InfrastructureOutput

cache:
  paths:
    - '/root/.terraform.d/**/*'
