version: 0.2

# Buildspec for building and deploying Java Lambda (Auth Service)

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven..."
      - mvn --version

  pre_build:
    commands:
      - echo "Environment - $ENVIRONMENT"
      - echo "Lambda Function - $LAMBDA_FUNCTION_NAME"
      - cd auth-service

  build:
    commands:
      - echo "Building Java application with Maven..."
      - mvn clean package -DskipTests
      
      - echo "Checking build artifacts..."
      - ls -la target/
      
      - echo "Cleaning up unnecessary jar files and using the fat jar..."
      - rm -f target/auth-service-1.0.0.jar
      - ls -la target/
      
      - echo "Checking if Lambda function exists..."
      - |
        if aws lambda get-function --function-name "$LAMBDA_FUNCTION_NAME" --region "$AWS_DEFAULT_REGION" 2>/dev/null; then
          echo "Lambda function exists, updating code..."
          
          # Wait for any pending updates to complete
          echo "Waiting for any pending updates to complete..."
          aws lambda wait function-updated --function-name "$LAMBDA_FUNCTION_NAME" --region "$AWS_DEFAULT_REGION" || echo "No pending updates"
          
          # Update function code
          aws lambda update-function-code \
            --function-name "$LAMBDA_FUNCTION_NAME" \
            --zip-file fileb://target/auth-service.jar \
            --region "$AWS_DEFAULT_REGION"
          
          echo "Waiting for function update to complete..."
          aws lambda wait function-updated --function-name "$LAMBDA_FUNCTION_NAME" --region "$AWS_DEFAULT_REGION"
          
          # Update function configuration only if needed
          echo "Updating function configuration..."
          aws lambda update-function-configuration \
            --function-name "$LAMBDA_FUNCTION_NAME" \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT,JWT_SECRET_NAME=${PROJECT_NAME}/jwt-secret,DYNAMODB_TABLE_NAME=${PROJECT_NAME}-users-${ENVIRONMENT}}" \
            --region "$AWS_DEFAULT_REGION" || echo "Configuration update failed, continuing..."
        else
          echo "Lambda function does not exist, creating..."
          if [ -z "$LAMBDA_ROLE_ARN" ]; then
            echo "ERROR: LAMBDA_ROLE_ARN environment variable is not set"
            exit 1
          fi
          
          aws lambda create-function \
            --function-name "$LAMBDA_FUNCTION_NAME" \
            --runtime java17 \
            --role "$LAMBDA_ROLE_ARN" \
            --handler com.ecommerce.platform.auth.AuthHandler::handleRequest \
            --zip-file fileb://target/auth-service.jar \
            --timeout 30 \
            --memory-size 512 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT,JWT_SECRET_NAME=${PROJECT_NAME}/jwt-secret,DYNAMODB_TABLE_NAME=${PROJECT_NAME}-users-${ENVIRONMENT}}" \
            --region "$AWS_DEFAULT_REGION"
        fi
      
      - echo "Waiting for Lambda function to be active..."
      - aws lambda wait function-active --function-name "$LAMBDA_FUNCTION_NAME" --region "$AWS_DEFAULT_REGION"
      - echo "Adding API Gateway invoke permission..."
      - |
        API_GATEWAY_NAME="${PROJECT_NAME}-api"
        echo "Looking for API Gateway: $API_GATEWAY_NAME"
        API_GATEWAY_ARN=$(aws apigateway get-rest-apis --query "items[?name=='$API_GATEWAY_NAME'].id" --output text --region "$AWS_DEFAULT_REGION")
        if [ ! -z "$API_GATEWAY_ARN" ] && [ "$API_GATEWAY_ARN" != "None" ]; then
          echo "Found API Gateway: $API_GATEWAY_ARN"
          ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          aws lambda add-permission \
            --function-name "$LAMBDA_FUNCTION_NAME" \
            --statement-id "AllowAPIGatewayInvoke" \
            --action "lambda:InvokeFunction" \
            --principal "apigateway.amazonaws.com" \
            --source-arn "arn:aws:execute-api:$AWS_DEFAULT_REGION:$ACCOUNT_ID:$API_GATEWAY_ARN/*/*" \
            --region "$AWS_DEFAULT_REGION" || echo "Permission may already exist"
        else
          echo "API Gateway not found, skipping permission setup"
        fi

  post_build:
    commands:
      - echo "Java Lambda deployment completed"
      - cd ..

artifacts:
  files:
    - auth-service/target/*.jar
  name: JavaLambdaOutput

cache:
  paths:
    - '/root/.m2/**/*'
