version: 0.2

# Buildspec for building and deploying Java Lambda (Auth Service)

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven..."
      - mvn --version

  pre_build:
    commands:
      - echo "Environment - $ENVIRONMENT"
      - echo "Lambda Function - $LAMBDA_FUNCTION_NAME"
      - cd auth-service

  build:
    commands:
      - echo "Building Java application with Maven..."
      - mvn clean package -DskipTests
      
      - echo "Checking if Lambda function exists..."
      - |
        if aws lambda get-function --function-name $LAMBDA_FUNCTION_NAME 2>/dev/null; then
          echo "Lambda function exists, updating code..."
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --zip-file fileb://target/auth-service-1.0-SNAPSHOT.jar
        else
          echo "Lambda function does not exist, creating..."
          aws lambda create-function \
            --function-name $LAMBDA_FUNCTION_NAME \
            --runtime java17 \
            --role $LAMBDA_ROLE_ARN \
            --handler com.futureim.auth.AuthHandler::handleRequest \
            --zip-file fileb://target/auth-service-1.0-SNAPSHOT.jar \
            --timeout 30 \
            --memory-size 512 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT,DYNAMODB_TABLE=$LAMBDA_FUNCTION_NAME-users}"
        fi
      
      - echo "Waiting for Lambda function to be active..."
      - aws lambda wait function-active --function-name $LAMBDA_FUNCTION_NAME

  post_build:
    commands:
      - echo "Java Lambda deployment completed"
      - cd ..

artifacts:
  files:
    - auth-service/target/*.jar
  name: JavaLambdaOutput

cache:
  paths:
    - '/root/.m2/**/*'
