version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Python version..."
      - python --version
      - pip --version

  pre_build:
    commands:
      - echo "Environment - $ENVIRONMENT"
      - echo "Project Name - $PROJECT_NAME"

  build:
    commands:
      - echo "Building and deploying Python Lambda functions..."
      - echo "Checking environment variables..."
      - echo "PROJECT_NAME - $PROJECT_NAME"
      - echo "ENVIRONMENT - $ENVIRONMENT"
      - echo "LAMBDA_ROLE_ARN - $LAMBDA_ROLE_ARN"
      - echo "AWS_DEFAULT_REGION - $AWS_DEFAULT_REGION"
      - |
        if [ -z "$LAMBDA_ROLE_ARN" ]; then
          echo "ERROR: LAMBDA_ROLE_ARN environment variable is not set"
          exit 1
        fi
      - echo "Deploying Analytics Service..."
      - cd analytics-service/src
      - pip install -r ../requirements.txt -t . --quiet --no-cache-dir
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -name "*.pyc" -delete 2>/dev/null || true
      - zip -r analytics-lambda.zip . -q
      - |
        FUNCTION_NAME="${PROJECT_NAME}-analytics-${ENVIRONMENT}"
        echo "Processing function: $FUNCTION_NAME"
        if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$AWS_DEFAULT_REGION" 2>/dev/null; then
          echo "Updating Analytics Lambda..."
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://analytics-lambda.zip \
            --region "$AWS_DEFAULT_REGION"
        else
          echo "Creating Analytics Lambda..."
          aws lambda create-function \
            --function-name "$FUNCTION_NAME" \
            --runtime python3.11 \
            --role "$LAMBDA_ROLE_ARN" \
            --handler handler.lambda_handler \
            --zip-file fileb://analytics-lambda.zip \
            --timeout 60 \
            --memory-size 512 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT}" \
            --region "$AWS_DEFAULT_REGION"
        fi
      - cd ../..
      - echo "Creating placeholder for Market Intelligence Hub..."
      - |
        cat > market_intelligence_placeholder.py << 'EOF'
        import json
        def lambda_handler(event, context):
            return {
                'statusCode': 501,
                'body': json.dumps({
                    'message': 'Market Intelligence Hub requires container deployment',
                    'service': 'market-intelligence-hub',
                    'status': 'requires_container_deployment'
                })
            }
        EOF
      - zip -r market-intelligence-placeholder.zip market_intelligence_placeholder.py
      - |
        FUNCTION_NAME="${PROJECT_NAME}-market-intelligence-${ENVIRONMENT}"
        echo "Processing placeholder function: $FUNCTION_NAME"
        if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$AWS_DEFAULT_REGION" 2>/dev/null; then
          echo "Updating Market Intelligence Lambda with placeholder..."
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://market-intelligence-placeholder.zip \
            --region "$AWS_DEFAULT_REGION"
        else
          echo "Creating Market Intelligence Lambda placeholder..."
          aws lambda create-function \
            --function-name "$FUNCTION_NAME" \
            --runtime python3.11 \
            --role "$LAMBDA_ROLE_ARN" \
            --handler market_intelligence_placeholder.lambda_handler \
            --zip-file fileb://market-intelligence-placeholder.zip \
            --timeout 60 \
            --memory-size 512 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT}" \
            --region "$AWS_DEFAULT_REGION"
        fi
      - echo "Deploying Demand Insights Engine..."
      - cd ai-systems/demand-insights-engine/src
      - pip install boto3 pandas numpy scikit-learn pyathena joblib scipy -t . --quiet --no-cache-dir
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -name "*.pyc" -delete 2>/dev/null || true
      - zip -r demand-insights-lambda.zip . -q
      - |
        FUNCTION_NAME="${PROJECT_NAME}-demand-insights-${ENVIRONMENT}"
        echo "Processing function: $FUNCTION_NAME"
        if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$AWS_DEFAULT_REGION" 2>/dev/null; then
          echo "Updating Demand Insights Lambda..."
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://demand-insights-lambda.zip \
            --region "$AWS_DEFAULT_REGION"
        else
          echo "Creating Demand Insights Lambda..."
          aws lambda create-function \
            --function-name "$FUNCTION_NAME" \
            --runtime python3.11 \
            --role "$LAMBDA_ROLE_ARN" \
            --handler handler.lambda_handler \
            --zip-file fileb://demand-insights-lambda.zip \
            --timeout 60 \
            --memory-size 1024 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT}" \
            --region "$AWS_DEFAULT_REGION"
        fi
      - cd ../../..
      - echo "Creating placeholder for Compliance Guardian..."
      - |
        cat > compliance_placeholder.py << 'EOF'
        import json
        def lambda_handler(event, context):
            return {
                'statusCode': 501,
                'body': json.dumps({
                    'message': 'Compliance Guardian requires container deployment',
                    'service': 'compliance-guardian',
                    'status': 'requires_container_deployment'
                })
            }
        EOF
      - zip -r compliance-placeholder.zip compliance_placeholder.py
      - |
        FUNCTION_NAME="${PROJECT_NAME}-compliance-guardian-${ENVIRONMENT}"
        echo "Processing placeholder function: $FUNCTION_NAME"
        if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$AWS_DEFAULT_REGION" 2>/dev/null; then
          echo "Updating Compliance Guardian Lambda with placeholder..."
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://compliance-placeholder.zip \
            --region "$AWS_DEFAULT_REGION"
        else
          echo "Creating Compliance Guardian Lambda placeholder..."
          aws lambda create-function \
            --function-name "$FUNCTION_NAME" \
            --runtime python3.11 \
            --role "$LAMBDA_ROLE_ARN" \
            --handler compliance_placeholder.lambda_handler \
            --zip-file fileb://compliance-placeholder.zip \
            --timeout 60 \
            --memory-size 512 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT}" \
            --region "$AWS_DEFAULT_REGION"
        fi
      - echo "Deploying Retail Copilot..."
      - cd ai-systems/retail-copilot/src
      - pip install -r ../requirements.txt -t . --quiet --no-cache-dir
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -name "*.pyc" -delete 2>/dev/null || true
      - zip -r retail-copilot-lambda.zip . -q
      - |
        FUNCTION_NAME="${PROJECT_NAME}-retail-copilot-${ENVIRONMENT}"
        echo "Processing function: $FUNCTION_NAME"
        if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$AWS_DEFAULT_REGION" 2>/dev/null; then
          echo "Updating Retail Copilot Lambda..."
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://retail-copilot-lambda.zip \
            --region "$AWS_DEFAULT_REGION"
        else
          echo "Creating Retail Copilot Lambda..."
          aws lambda create-function \
            --function-name "$FUNCTION_NAME" \
            --runtime python3.11 \
            --role "$LAMBDA_ROLE_ARN" \
            --handler handler.lambda_handler \
            --zip-file fileb://retail-copilot-lambda.zip \
            --timeout 60 \
            --memory-size 1024 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT}" \
            --region "$AWS_DEFAULT_REGION"
        fi
      - cd ../../..
      - echo "Deploying Global Market Pulse..."
      - cd ai-systems/global-market-pulse/src
      - pip install -r ../requirements.txt -t . --quiet --no-cache-dir
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -name "*.pyc" -delete 2>/dev/null || true
      - zip -r global-market-pulse-lambda.zip . -q
      - |
        FUNCTION_NAME="${PROJECT_NAME}-global-market-pulse-${ENVIRONMENT}"
        echo "Processing function: $FUNCTION_NAME"
        if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$AWS_DEFAULT_REGION" 2>/dev/null; then
          echo "Updating Global Market Pulse Lambda..."
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://global-market-pulse-lambda.zip \
            --region "$AWS_DEFAULT_REGION"
        else
          echo "Creating Global Market Pulse Lambda..."
          aws lambda create-function \
            --function-name "$FUNCTION_NAME" \
            --runtime python3.11 \
            --role "$LAMBDA_ROLE_ARN" \
            --handler handler.lambda_handler \
            --zip-file fileb://global-market-pulse-lambda.zip \
            --timeout 60 \
            --memory-size 1024 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT}" \
            --region "$AWS_DEFAULT_REGION"
        fi
      - cd ../../..

  post_build:
    commands:
      - echo "Python Lambdas deployment completed"
      - echo "Market Intelligence Hub and Compliance Guardian deployed as placeholders"
      - echo "These services require container deployment due to large ML dependencies"

artifacts:
  files:
    - '**/*.zip'
  name: PythonLambdasOutput

cache:
  paths:
    - '/root/.cache/pip/**/*'