version: 0.2

# Buildspec for building and deploying Python Lambdas

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Python version..."
      - python --version
      - pip --version

  pre_build:
    commands:
      - echo "Environment - $ENVIRONMENT"
      - echo "Project Name - $PROJECT_NAME"

  build:
    commands:
      - echo "Building and deploying Python Lambda functions..."
      
      # Analytics Service
      - echo "Deploying Analytics Service..."
      - cd analytics-service/src
      - pip install -r ../requirements.txt -t .
      - zip -r analytics-lambda.zip .
      - |
        FUNCTION_NAME="${PROJECT_NAME}-analytics-${ENVIRONMENT}"
        if aws lambda get-function --function-name $FUNCTION_NAME 2>/dev/null; then
          echo "Updating Analytics Lambda..."
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://analytics-lambda.zip
        else
          echo "Creating Analytics Lambda..."
          aws lambda create-function \
            --function-name $FUNCTION_NAME \
            --runtime python3.11 \
            --role $LAMBDA_ROLE_ARN \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://analytics-lambda.zip \
            --timeout 60 \
            --memory-size 512 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT}"
        fi
      - cd ../..
      
      # Market Intelligence Hub
      - echo "Deploying Market Intelligence Hub..."
      - cd ai-systems/market-intelligence-hub
      - pip install -r requirements.txt -t .
      - zip -r market-intelligence-lambda.zip .
      - |
        FUNCTION_NAME="${PROJECT_NAME}-market-intelligence-${ENVIRONMENT}"
        if aws lambda get-function --function-name $FUNCTION_NAME 2>/dev/null; then
          echo "Updating Market Intelligence Lambda..."
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://market-intelligence-lambda.zip
        else
          echo "Creating Market Intelligence Lambda..."
          aws lambda create-function \
            --function-name $FUNCTION_NAME \
            --runtime python3.11 \
            --role $LAMBDA_ROLE_ARN \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://market-intelligence-lambda.zip \
            --timeout 60 \
            --memory-size 1024 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT}"
        fi
      - cd ../..
      
      # Demand Insights Engine
      - echo "Deploying Demand Insights Engine..."
      - cd ai-systems/demand-insights-engine
      - pip install -r requirements.txt -t .
      - zip -r demand-insights-lambda.zip .
      - |
        FUNCTION_NAME="${PROJECT_NAME}-demand-insights-${ENVIRONMENT}"
        if aws lambda get-function --function-name $FUNCTION_NAME 2>/dev/null; then
          echo "Updating Demand Insights Lambda..."
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://demand-insights-lambda.zip
        else
          echo "Creating Demand Insights Lambda..."
          aws lambda create-function \
            --function-name $FUNCTION_NAME \
            --runtime python3.11 \
            --role $LAMBDA_ROLE_ARN \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://demand-insights-lambda.zip \
            --timeout 60 \
            --memory-size 1024 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT}"
        fi
      - cd ../..
      
      # Compliance Guardian
      - echo "Deploying Compliance Guardian..."
      - cd ai-systems/compliance-guardian
      - pip install -r requirements.txt -t .
      - zip -r compliance-lambda.zip .
      - |
        FUNCTION_NAME="${PROJECT_NAME}-compliance-guardian-${ENVIRONMENT}"
        if aws lambda get-function --function-name $FUNCTION_NAME 2>/dev/null; then
          echo "Updating Compliance Guardian Lambda..."
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://compliance-lambda.zip
        else
          echo "Creating Compliance Guardian Lambda..."
          aws lambda create-function \
            --function-name $FUNCTION_NAME \
            --runtime python3.11 \
            --role $LAMBDA_ROLE_ARN \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://compliance-lambda.zip \
            --timeout 60 \
            --memory-size 1024 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT}"
        fi
      - cd ../..
      
      # Retail Copilot
      - echo "Deploying Retail Copilot..."
      - cd ai-systems/retail-copilot
      - pip install -r requirements.txt -t .
      - zip -r retail-copilot-lambda.zip .
      - |
        FUNCTION_NAME="${PROJECT_NAME}-retail-copilot-${ENVIRONMENT}"
        if aws lambda get-function --function-name $FUNCTION_NAME 2>/dev/null; then
          echo "Updating Retail Copilot Lambda..."
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://retail-copilot-lambda.zip
        else
          echo "Creating Retail Copilot Lambda..."
          aws lambda create-function \
            --function-name $FUNCTION_NAME \
            --runtime python3.11 \
            --role $LAMBDA_ROLE_ARN \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://retail-copilot-lambda.zip \
            --timeout 60 \
            --memory-size 1024 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT}"
        fi
      - cd ../..
      
      # Global Market Pulse
      - echo "Deploying Global Market Pulse..."
      - cd ai-systems/global-market-pulse
      - pip install -r requirements.txt -t .
      - zip -r global-market-pulse-lambda.zip .
      - |
        FUNCTION_NAME="${PROJECT_NAME}-global-market-pulse-${ENVIRONMENT}"
        if aws lambda get-function --function-name $FUNCTION_NAME 2>/dev/null; then
          echo "Updating Global Market Pulse Lambda..."
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://global-market-pulse-lambda.zip
        else
          echo "Creating Global Market Pulse Lambda..."
          aws lambda create-function \
            --function-name $FUNCTION_NAME \
            --runtime python3.11 \
            --role $LAMBDA_ROLE_ARN \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://global-market-pulse-lambda.zip \
            --timeout 60 \
            --memory-size 1024 \
            --environment Variables="{ENVIRONMENT=$ENVIRONMENT}"
        fi
      - cd ../..

  post_build:
    commands:
      - echo "Python Lambdas deployment completed"

artifacts:
  files:
    - '**/*.zip'
  name: PythonLambdasOutput

cache:
  paths:
    - '/root/.cache/pip/**/*'
