/**
 * eCommerce AI Analytics Platform - Architecture Diagram
 * 
 * Interactive visualization of the complete system architecture including:
 * - 5 AI Systems
 * - User Interface
 * - DMS Platform with Data Migration
 * - Numbered process flow
 * - VPC and subnet boundaries
 */

import React, { useState } from 'react';
import './ArchitectureDiagram.css';

interface ProcessStep {
  id: number;
  title: string;
  description: string;
  component: string;
}

const ArchitectureDiagram: React.FC = () => {
  const [selectedStep, setSelectedStep] = useState<number | null>(null);
  const [hoveredComponent, setHoveredComponent] = useState<string | null>(null);

  const processSteps: ProcessStep[] = [
    {
      id: 1,
      title: "User Authentication",
      description: "User logs in via React frontend. JWT token generated by Auth Lambda and stored in browser.",
      component: "frontend"
    },
    {
      id: 2,
      title: "Dashboard Access",
      description: "User selects one of 5 AI system dashboards. JWT token passed in Authorization header.",
      component: "frontend"
    },
    {
      id: 3,
      title: "API Request",
      description: "Frontend sends HTTPS request to API Gateway with JWT token for authentication.",
      component: "api-gateway"
    },
    {
      id: 4,
      title: "Token Verification",
      description: "Lambda Authorizer verifies JWT token against secret in Secrets Manager.",
      component: "authorizer"
    },
    {
      id: 5,
      title: "Analytics Query",
      description: "Analytics Lambda receives request and prepares Athena query with SQL injection prevention.",
      component: "analytics-lambda"
    },
    {
      id: 6,
      title: "Athena Execution",
      description: "Athena executes SQL query against Glue Catalog tables pointing to S3 prod data.",
      component: "athena"
    },
    {
      id: 7,
      title: "Data Retrieval",
      description: "Athena reads Parquet files from S3 prod buckets and returns results.",
      component: "s3-prod"
    },
    {
      id: 8,
      title: "Response to User",
      description: "Analytics data flows back through Lambda → API Gateway → Frontend for visualization.",
      component: "frontend"
    },
    {
      id: 9,
      title: "DMS Replication (Continuous)",
      description: "DMS continuously replicates changes from on-premise MySQL to S3 raw buckets using CDC.",
      component: "dms"
    },
    {
      id: 10,
      title: "Raw Data Processing",
      description: "S3 event triggers EventBridge → Batch job validates, deduplicates, and writes to curated bucket.",
      component: "batch-raw"
    },
    {
      id: 11,
      title: "Curated to Prod",
      description: "S3 event triggers EventBridge → Batch job transforms data and writes to prod bucket.",
      component: "batch-curated"
    },
    {
      id: 12,
      title: "Catalog Update",
      description: "Glue Crawler scans prod bucket, infers schema, and updates Glue Catalog for Athena queries.",
      component: "glue"
    }
  ];

  return (
    <div className="architecture-container">
      <div className="architecture-header">
        <h1>eCommerce AI Analytics Platform - End-to-End Architecture</h1>
        <p className="subtitle">Interactive System Architecture with Numbered Process Flow</p>
      </div>

      {/* Process Flow Legend */}
      <div className="process-flow-panel">
        <h2>Process Flow Steps</h2>
        <div className="process-steps">
          {processSteps.map((step) => (
            <div
              key={step.id}
              className={`process-step ${selectedStep === step.id ? 'selected' : ''} ${hoveredComponent === step.component ? 'highlighted' : ''}`}
              onClick={() => setSelectedStep(selectedStep === step.id ? null : step.id)}
            >
              <div className="step-number">{step.id}</div>
              <div className="step-content">
                <div className="step-title">{step.title}</div>
                {selectedStep === step.id && (
                  <div className="step-description">{step.description}</div>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Main Architecture Diagram */}
      <div className="architecture-diagram">
        
        {/* On-Premise Boundary */}
        <div className="boundary on-premise">
          <div className="boundary-label">On-Premise Infrastructure</div>
          <div 
            className={`component mysql ${hoveredComponent === 'dms' ? 'highlight' : ''}`}
            onMouseEnter={() => setHoveredComponent('dms')}
            onMouseLeave={() => setHoveredComponent(null)}
          >
            <div className="component-icon">🗄️</div>
            <div className="component-name">MySQL Database</div>
            <div className="component-detail">172.20.10.4:3306</div>
            <div className="component-detail">26 Tables</div>
            <div className="flow-number">9</div>
          </div>
        </div>

        {/* AWS Cloud Boundary */}
        <div className="boundary aws-cloud">
          <div className="boundary-label">AWS Cloud (us-east-1)</div>

          {/* VPC */}
          <div className="vpc-boundary">
            <div className="vpc-label">VPC (10.0.0.0/16)</div>

            {/* Public Subnet */}
            <div className="subnet public-subnet">
              <div className="subnet-label">Public Subnet (10.0.1.0/24)</div>
              
              <div 
                className={`component api-gateway ${hoveredComponent === 'api-gateway' ? 'highlight' : ''}`}
                onMouseEnter={() => setHoveredComponent('api-gateway')}
                onMouseLeave={() => setHoveredComponent(null)}
              >
                <div className="component-icon">🌐</div>
                <div className="component-name">API Gateway</div>
                <div className="component-detail">REST API</div>
                <div className="component-detail">/auth/* /analytics/*</div>
                <div className="flow-number">3</div>
              </div>

              <div 
                className={`component waf ${hoveredComponent === 'api-gateway' ? 'highlight' : ''}`}
                onMouseEnter={() => setHoveredComponent('api-gateway')}
                onMouseLeave={() => setHoveredComponent(null)}
              >
                <div className="component-icon">🛡️</div>
                <div className="component-name">WAF</div>
                <div className="component-detail">OWASP Rules</div>
              </div>
            </div>

            {/* Private Subnet 1 - Lambda Functions */}
            <div className="subnet private-subnet">
              <div className="subnet-label">Private Subnet 1 (10.0.2.0/24)</div>
              
              <div 
                className={`component lambda ${hoveredComponent === 'authorizer' ? 'highlight' : ''}`}
                onMouseEnter={() => setHoveredComponent('authorizer')}
                onMouseLeave={() => setHoveredComponent(null)}
              >
                <div className="component-icon">λ</div>
                <div className="component-name">Auth Lambda</div>
                <div className="component-detail">Java 17</div>
                <div className="component-detail">Register/Login</div>
                <div className="flow-number">1</div>
              </div>

              <div 
                className={`component lambda ${hoveredComponent === 'authorizer' ? 'highlight' : ''}`}
                onMouseEnter={() => setHoveredComponent('authorizer')}
                onMouseLeave={() => setHoveredComponent(null)}
              >
                <div className="component-icon">λ</div>
                <div className="component-name">Authorizer</div>
                <div className="component-detail">JWT Verification</div>
                <div className="flow-number">4</div>
              </div>

              <div 
                className={`component lambda ${hoveredComponent === 'analytics-lambda' ? 'highlight' : ''}`}
                onMouseEnter={() => setHoveredComponent('analytics-lambda')}
                onMouseLeave={() => setHoveredComponent(null)}
              >
                <div className="component-icon">λ</div>
                <div className="component-name">Analytics Lambda</div>
                <div className="component-detail">Python 3.11</div>
                <div className="component-detail">Athena Queries</div>
                <div className="flow-number">5</div>
              </div>
            </div>

            {/* Private Subnet 2 - Data Processing */}
            <div className="subnet private-subnet">
              <div className="subnet-label">Private Subnet 2 (10.0.3.0/24)</div>
              
              <div 
                className={`component dms ${hoveredComponent === 'dms' ? 'highlight' : ''}`}
                onMouseEnter={() => setHoveredComponent('dms')}
                onMouseLeave={() => setHoveredComponent(null)}
              >
                <div className="component-icon">🔄</div>
                <div className="component-name">DMS Instance</div>
                <div className="component-detail">CDC Enabled</div>
                <div className="component-detail">MySQL → S3</div>
                <div className="flow-number">9</div>
              </div>

              <div 
                className={`component batch ${hoveredComponent === 'batch-raw' ? 'highlight' : ''}`}
                onMouseEnter={() => setHoveredComponent('batch-raw')}
                onMouseLeave={() => setHoveredComponent(null)}
              >
                <div className="component-icon">⚙️</div>
                <div className="component-name">Batch (Raw→Curated)</div>
                <div className="component-detail">Validation</div>
                <div className="component-detail">Deduplication</div>
                <div className="flow-number">10</div>
              </div>

              <div 
                className={`component batch ${hoveredComponent === 'batch-curated' ? 'highlight' : ''}`}
                onMouseEnter={() => setHoveredComponent('batch-curated')}
                onMouseLeave={() => setHoveredComponent(null)}
              >
                <div className="component-icon">⚙️</div>
                <div className="component-name">Batch (Curated→Prod)</div>
                <div className="component-detail">Transformation</div>
                <div className="component-detail">Optimization</div>
                <div className="flow-number">11</div>
              </div>
            </div>
          </div>

          {/* Managed Services (Outside VPC) */}
          <div className="managed-services">
            <div className="service-group">
              <div className="service-group-label">Data Services</div>
              
              <div 
                className={`component s3 ${hoveredComponent === 's3-prod' ? 'highlight' : ''}`}
                onMouseEnter={() => setHoveredComponent('s3-prod')}
                onMouseLeave={() => setHoveredComponent(null)}
              >
                <div className="component-icon">🪣</div>
                <div className="component-name">S3 Data Lake</div>
                <div className="component-detail">Raw / Curated / Prod</div>
                <div className="component-detail">Parquet Format</div>
                <div className="flow-number">7</div>
              </div>

              <div 
                className={`component glue ${hoveredComponent === 'glue' ? 'highlight' : ''}`}
                onMouseEnter={() => setHoveredComponent('glue')}
                onMouseLeave={() => setHoveredComponent(null)}
              >
                <div className="component-icon">🔍</div>
                <div className="component-name">Glue Catalog</div>
                <div className="component-detail">Schema Discovery</div>
                <div className="component-detail">26 Tables</div>
                <div className="flow-number">12</div>
              </div>

              <div 
                className={`component athena ${hoveredComponent === 'athena' ? 'highlight' : ''}`}
                onMouseEnter={() => setHoveredComponent('athena')}
                onMouseLeave={() => setHoveredComponent(null)}
              >
                <div className="component-icon">📊</div>
                <div className="component-name">Athena</div>
                <div className="component-detail">SQL Queries</div>
                <div className="component-detail">Serverless</div>
                <div className="flow-number">6</div>
              </div>
            </div>

            <div className="service-group">
              <div className="service-group-label">Storage & Security</div>
              
              <div className="component dynamodb">
                <div className="component-icon">💾</div>
                <div className="component-name">DynamoDB</div>
                <div className="component-detail">Users Table</div>
              </div>

              <div className="component secrets">
                <div className="component-icon">🔐</div>
                <div className="component-name">Secrets Manager</div>
                <div className="component-detail">JWT Secret</div>
                <div className="component-detail">MySQL Password</div>
              </div>

              <div className="component eventbridge">
                <div className="component-icon">📡</div>
                <div className="component-name">EventBridge</div>
                <div className="component-detail">S3 Events</div>
                <div className="component-detail">Batch Triggers</div>
              </div>
            </div>
          </div>
        </div>

        {/* User/Frontend Boundary */}
        <div className="boundary user-zone">
          <div className="boundary-label">User Zone</div>
          
          <div 
            className={`component frontend ${hoveredComponent === 'frontend' ? 'highlight' : ''}`}
            onMouseEnter={() => setHoveredComponent('frontend')}
            onMouseLeave={() => setHoveredComponent(null)}
          >
            <div className="component-icon">💻</div>
            <div className="component-name">React Frontend</div>
            <div className="component-detail">TypeScript + Material-UI</div>
            <div className="component-detail">5 AI System Dashboards</div>
            <div className="flow-number">2</div>
          </div>

          <div className="user-icon">👤</div>
          <div className="user-label">End User</div>
        </div>

        {/* 5 AI Systems Panel */}
        <div className="ai-systems-panel">
          <h3>5 AI Systems</h3>
          <div className="ai-systems-grid">
            <div className="ai-system">
              <div className="ai-icon">📈</div>
              <div className="ai-name">Market Intelligence Hub</div>
              <div className="ai-tech">ARIMA, Prophet, LSTM</div>
            </div>
            <div className="ai-system">
              <div className="ai-icon">🎯</div>
              <div className="ai-name">Demand Insights Engine</div>
              <div className="ai-tech">XGBoost, K-Means</div>
            </div>
            <div className="ai-system">
              <div className="ai-icon">🛡️</div>
              <div className="ai-name">Compliance Guardian</div>
              <div className="ai-tech">Isolation Forest, GBM</div>
            </div>
            <div className="ai-system">
              <div className="ai-icon">🤖</div>
              <div className="ai-name">Retail Copilot</div>
              <div className="ai-tech">LLM, NL to SQL</div>
            </div>
            <div className="ai-system">
              <div className="ai-icon">🌍</div>
              <div className="ai-name">Global Market Pulse</div>
              <div className="ai-tech">Geospatial, MCDA</div>
            </div>
          </div>
        </div>

        {/* Data Flow Arrows */}
        <svg className="flow-arrows" xmlns="http://www.w3.org/2000/svg">
          {/* User to Frontend */}
          <defs>
            <marker id="arrowhead" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto">
              <polygon points="0 0, 10 3, 0 6" fill="#4CAF50" />
            </marker>
          </defs>
          
          {/* Main data flow path */}
          <path d="M 100 50 L 300 50" stroke="#4CAF50" strokeWidth="3" markerEnd="url(#arrowhead)" className="flow-path" />
          <path d="M 300 100 L 500 100" stroke="#2196F3" strokeWidth="3" markerEnd="url(#arrowhead)" className="flow-path" />
          <path d="M 500 150 L 700 150" stroke="#FF9800" strokeWidth="3" markerEnd="url(#arrowhead)" className="flow-path" />
        </svg>
      </div>

      {/* Legend */}
      <div className="legend">
        <h3>Legend</h3>
        <div className="legend-items">
          <div className="legend-item">
            <div className="legend-color" style={{backgroundColor: '#e3f2fd'}}></div>
            <span>Public Subnet</span>
          </div>
          <div className="legend-item">
            <div className="legend-color" style={{backgroundColor: '#f3e5f5'}}></div>
            <span>Private Subnet</span>
          </div>
          <div className="legend-item">
            <div className="legend-color" style={{backgroundColor: '#fff3e0'}}></div>
            <span>Managed Services</span>
          </div>
          <div className="legend-item">
            <div className="legend-color" style={{backgroundColor: '#e8f5e9'}}></div>
            <span>On-Premise</span>
          </div>
          <div className="legend-item">
            <div className="flow-number-legend">1</div>
            <span>Process Flow Step</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ArchitectureDiagram;
