AWSTemplateFormatVersion: '2010-09-09'
Description: 'CI/CD Pipeline for eCommerce AI Analytics Platform - Dev and Prod Environments'

Parameters:
  ProjectName:
    Type: String
    Default: ecommerce-ai-platform
    Description: Project name used for resource naming
  
  GitHubRepo:
    Type: String
    Description: GitHub repository name (e.g., username/repo-name)
  
  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch to track
  
  GitHubToken:
    Type: String
    NoEcho: true
    Description: GitHub personal access token for CodePipeline
  
  DevApprovalEmail:
    Type: String
    Description: Email address for dev deployment approvals
  
  ProdApprovalEmail:
    Type: String
    Description: Email address for prod deployment approvals

Resources:
  # ============================================
  # S3 Buckets for Artifacts
  # ============================================
  
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-pipeline-artifacts'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldArtifacts
            Status: Enabled
            ExpirationInDays: 30
  
  DevArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-artifacts-dev'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  
  ProdArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-artifacts-prod'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  
  # ============================================
  # ECR Repositories
  # ============================================
  
  DataProcessingECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${ProjectName}-data-processing'
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
  
  # ============================================
  # SNS Topics for Approvals
  # ============================================
  
  DevApprovalTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-dev-approval'
      DisplayName: Dev Deployment Approval
      Subscription:
        - Endpoint: !Ref DevApprovalEmail
          Protocol: email
  
  ProdApprovalTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-prod-approval'
      DisplayName: Production Deployment Approval
      Subscription:
        - Endpoint: !Ref ProdApprovalEmail
          Protocol: email
  
  # ============================================
  # IAM Roles
  # ============================================
  
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-codepipeline-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codebuild:*
                  - sns:Publish
                  - iam:PassRole
                Resource: '*'
  
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-codebuild-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*'
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Sub '${ArtifactBucket.Arn}/*'
                  - !GetAtt DevArtifactBucket.Arn
                  - !Sub '${DevArtifactBucket.Arn}/*'
                  - !GetAtt ProdArtifactBucket.Arn
                  - !Sub '${ProdArtifactBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - ecr:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ProjectName}/*'
  
  # ============================================
  # CodeBuild Projects
  # ============================================
  
  DevBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}-dev-build'
      Description: Build and deploy to dev environment
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: ENVIRONMENT
            Value: dev
      Source:
        Type: CODEPIPELINE
        BuildSpec: deployment/deployment-pipeline/buildspec-dev.yml
      TimeoutInMinutes: 60
      Cache:
        Type: S3
        Location: !Sub '${ArtifactBucket}/build-cache'
  
  ProdBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}-prod-build'
      Description: Build and deploy to production environment
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_LARGE
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: ENVIRONMENT
            Value: prod
      Source:
        Type: CODEPIPELINE
        BuildSpec: deployment/deployment-pipeline/buildspec-prod.yml
      TimeoutInMinutes: 90
      Cache:
        Type: S3
        Location: !Sub '${ArtifactBucket}/build-cache'
  
  # ============================================
  # CodePipeline
  # ============================================
  
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${ProjectName}-pipeline'
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        # Stage 1: Source
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: !Select [0, !Split ['/', !Ref GitHubRepo]]
                Repo: !Select [1, !Split ['/', !Ref GitHubRepo]]
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceOutput
        
        # Stage 2: Build and Deploy to Dev
        - Name: Build-Dev
          Actions:
            - Name: BuildAndDeployDev
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref DevBuildProject
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: DevBuildOutput
        
        # Stage 3: Dev Approval (Optional)
        - Name: Approve-Dev
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                NotificationArn: !Ref DevApprovalTopic
                CustomData: 'Please review the dev deployment and approve to proceed to production.'
        
        # Stage 4: Build and Deploy to Prod
        - Name: Build-Prod
          Actions:
            - Name: BuildAndDeployProd
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref ProdBuildProject
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: ProdBuildOutput
        
        # Stage 5: Production Approval
        - Name: Approve-Prod
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                NotificationArn: !Ref ProdApprovalTopic
                CustomData: 'Production deployment completed. Please verify and approve.'
  
  # ============================================
  # CloudWatch Event Rule for GitHub Webhook
  # ============================================
  
  PipelineTriggerRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-pipeline-trigger'
      Description: Trigger pipeline on GitHub push
      EventPattern:
        source:
          - aws.codepipeline
        detail-type:
          - CodePipeline Pipeline Execution State Change
        detail:
          state:
            - STARTED
            - SUCCEEDED
            - FAILED
      State: ENABLED
      Targets:
        - Arn: !Ref DevApprovalTopic
          Id: NotifyOnPipelineChange

Outputs:
  PipelineName:
    Description: Name of the CodePipeline
    Value: !Ref Pipeline
    Export:
      Name: !Sub '${ProjectName}-pipeline-name'
  
  PipelineUrl:
    Description: URL to the CodePipeline console
    Value: !Sub 'https://console.aws.amazon.com/codesuite/codepipeline/pipelines/${Pipeline}/view'
  
  DevBuildProjectName:
    Description: Name of the dev build project
    Value: !Ref DevBuildProject
  
  ProdBuildProjectName:
    Description: Name of the prod build project
    Value: !Ref ProdBuildProject
  
  ArtifactBucketName:
    Description: S3 bucket for pipeline artifacts
    Value: !Ref ArtifactBucket
  
  ECRRepositoryUri:
    Description: ECR repository URI for data processing
    Value: !GetAtt DataProcessingECR.RepositoryUri
